export const Scores = {
  "0": {
    "bne-ence": [[9, 16], [13, 16]],
    "bne-forz": [[7, 16]],
    "cplx-out": [[9, 16]],
    "cplx-vita": [[1, 16]],
    "eter-bne": [[14, 16]],
    "eter-mibr": [[11, 16], [13, 16]],
    "eter-spir": [[11, 16]],
    "forz-vita": [[12, 16], [9, 16], [16, 12]],
    "g2-ence": [[16, 9], [16, 19], [16, 7]],
    "ihc-astr": [[2, 16]],
    "ihc-cplx": [[13, 16]],
    "ihc-imp": [[12, 16], [10, 16], [16, 11]],
    "ihc-ren": [[16, 12], [16, 10]],
    "imp-bne": [[12, 16]],
    "imp-forz": [[16, 5], [16, 5]],
    "liq-astr": [[16, 13], [16, 14]],
    "liq-cplx": [[16, 12], [16, 12]],
    "liq-g2": [[6, 16]],
    "liq-imp": [[10, 16]],
    "mibr-astr": [[13, 16]],
    "mibr-bne": [[10, 16], [8, 16], [16, 13]],
    "nine-ence": [[7, 16]],
    "nine-liq": [[11, 16], [11, 16]],
    "nine-mibr": [[14, 16]],
    "out-ence": [[6, 16]],
    "out-forz": [[16, 11], [16, 10], [12, 16]],
    "out-mibr": [[16, 14]],
    "ren-eter": [[2, 16]],
    "ren-forz": [[9, 16]],
    "spir-astr": [[16, 6], [16, 12]],
    "spir-g2": [[17, 19]],
    "spir-imp": [[16, 6]],
    "vita-astr": [[16, 8]
    ]
  },
  "1": {},
  "2": {},
  "key": "event_19"
}
export const ChallengerResults = [
  {
    "l": 0,
    "w": 3,
    "opponents": [
      "liq",
      "spir",
      "ence"
    ],
    "buchholz": 5,
    "code": "g2",
    "name": "G2 Esports",
    "seed": 10,
    "description": "EUB #5",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/g2_large.png",
    "standing": 1,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "1st",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 0,
    "w": 3,
    "opponents": [
      "cplx",
      "astr",
      "forz"
    ],
    "buchholz": -4,
    "code": "vita",
    "name": "Team Vitality",
    "seed": 13,
    "description": "EUA #6",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/vita_large.png",
    "standing": 2,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "2nd",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "nine",
      "out",
      "g2",
      "bne"
    ],
    "buchholz": 3,
    "code": "ence",
    "name": "ENCE",
    "seed": 9,
    "description": "EUB #4",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/ence_large.png",
    "standing": 3,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "3rd",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "imp",
      "g2",
      "eter",
      "astr"
    ],
    "buchholz": 1,
    "code": "spir",
    "name": "Team Spirit",
    "seed": 18,
    "description": "EUB #8",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/spir_large.png",
    "standing": 4,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "4th",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "mibr",
      "ence",
      "cplx",
      "forz"
    ],
    "buchholz": -2,
    "code": "out",
    "name": "Outsiders",
    "seed": 19,
    "description": "EUA #8",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/out_large.png",
    "standing": 5,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "5th",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "spir",
      "liq",
      "bne",
      "ihc",
      "forz"
    ],
    "buchholz": 1,
    "code": "imp",
    "name": "Imperial Esports",
    "seed": 15,
    "description": "AM #3",
    "region": "AM",
    "logo": "https://major.ieb.im/images/antwerp2022/imp_large.png",
    "standing": 6,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "6th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "eter",
      "forz",
      "imp",
      "ence",
      "mibr"
    ],
    "buchholz": -1,
    "code": "bne",
    "name": "Bad News Eagles",
    "seed": 16,
    "description": "EUB #7",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/bne_large.png",
    "standing": 7,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "7th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "g2",
      "imp",
      "nine",
      "cplx",
      "astr"
    ],
    "buchholz": -2,
    "code": "liq",
    "name": "Team Liquid",
    "seed": 23,
    "description": "AM #5",
    "region": "AM",
    "logo": "https://major.ieb.im/images/antwerp2022/liq_large.png",
    "standing": 8,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "8th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "ren",
      "bne",
      "vita",
      "out",
      "imp"
    ],
    "buchholz": 4,
    "code": "forz",
    "name": "forZe",
    "seed": 11,
    "description": "EUA #5",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/forz_large.png",
    "standing": 9,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "9th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "ihc",
      "vita",
      "mibr",
      "spir",
      "liq"
    ],
    "buchholz": 3,
    "code": "astr",
    "name": "Astralis",
    "seed": 12,
    "description": "EUB #6",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/astr_large.png",
    "standing": 10,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "10th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "out",
      "nine",
      "astr",
      "eter",
      "bne"
    ],
    "buchholz": -3,
    "code": "mibr",
    "name": "MIBR",
    "seed": 14,
    "description": "AM #2",
    "region": "AM",
    "logo": "https://major.ieb.im/images/antwerp2022/mibr_large.png",
    "standing": 11,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "11th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "vita",
      "ihc",
      "out",
      "liq"
    ],
    "buchholz": 4,
    "code": "cplx",
    "name": "Complexity Gaming",
    "seed": 20,
    "description": "AM #4",
    "region": "AM",
    "logo": "https://major.ieb.im/images/antwerp2022/cplx_large.png",
    "standing": 12,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "12th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "bne",
      "ren",
      "spir",
      "mibr"
    ],
    "buchholz": -1,
    "code": "eter",
    "name": "Eternal Fire",
    "seed": 17,
    "description": "EUA #7",
    "region": "EU",
    "logo": "https://major.ieb.im/images/antwerp2022/eter_large.png",
    "standing": 13,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "13th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "astr",
      "cplx",
      "ren",
      "imp"
    ],
    "buchholz": -5,
    "code": "ihc",
    "name": "IHC Esports",
    "seed": 21,
    "description": "AP #1",
    "region": "AP",
    "logo": "https://major.ieb.im/images/antwerp2022/ihc_large.png",
    "standing": 14,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "14th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 0,
    "opponents": [
      "ence",
      "mibr",
      "liq"
    ],
    "buchholz": 2,
    "code": "nine",
    "name": "9z Team",
    "seed": 24,
    "description": "AM #6",
    "region": "AM",
    "logo": "https://major.ieb.im/images/antwerp2022/nine_large.png",
    "standing": 15,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "15th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 0,
    "opponents": [
      "forz",
      "eter",
      "ihc"
    ],
    "buchholz": -5,
    "code": "ren",
    "name": "Renegades",
    "seed": 22,
    "description": "AP #2",
    "region": "AP",
    "logo": "https://major.ieb.im/images/antwerp2022/ren_large.png",
    "standing": 16,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "16th",
    "elim": true,
    "adv": false,
    "currentRound": false
  }
];
