export const Scores = {
  "0": {
  },
  "1": {
  },
  "2": {
  },
  "key": "event_20"
}

export const ChallengerResults = [
  {
    "l": 0,
    "w": 3,
    "opponents": [
      "liq",
      "spir",
      "ence"
    ],
    "buchholtz": 5,
    "code": "g2",
    "name": "G2 Esports",
    "seed": 10,
    "description": "EUB #5",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/g2_large.png",
    "standing": 1,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "1st",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 0,
    "w": 3,
    "opponents": [
      "cplx",
      "astr",
      "forz"
    ],
    "buchholtz": -4,
    "code": "vita",
    "name": "Team Vitality",
    "seed": 13,
    "description": "EUA #6",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/vita_large.png",
    "standing": 2,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "2nd",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "nine",
      "out",
      "g2",
      "bne"
    ],
    "buchholtz": 3,
    "code": "ence",
    "name": "ENCE",
    "seed": 9,
    "description": "EUB #4",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/ence_large.png",
    "standing": 3,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "3rd",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "imp",
      "g2",
      "eter",
      "astr"
    ],
    "buchholtz": 1,
    "code": "spir",
    "name": "Team Spirit",
    "seed": 18,
    "description": "EUB #8",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/spir_large.png",
    "standing": 4,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "4th",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "mibr",
      "ence",
      "cplx",
      "forz"
    ],
    "buchholtz": -2,
    "code": "out",
    "name": "Outsiders",
    "seed": 19,
    "description": "EUA #8",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/out_large.png",
    "standing": 5,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "5th",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "spir",
      "liq",
      "bne",
      "ihc",
      "forz"
    ],
    "buchholtz": 1,
    "code": "imp",
    "name": "Imperial Esports",
    "seed": 15,
    "description": "AM #3",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/imp_large.png",
    "standing": 6,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "6th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "eter",
      "forz",
      "imp",
      "ence",
      "mibr"
    ],
    "buchholtz": -1,
    "code": "bne",
    "name": "Bad News Eagles",
    "seed": 16,
    "description": "EUB #7",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/bne_large.png",
    "standing": 7,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "7th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "g2",
      "imp",
      "nine",
      "cplx",
      "astr"
    ],
    "buchholtz": -2,
    "code": "liq",
    "name": "Team Liquid",
    "seed": 23,
    "description": "AM #5",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/liq_large.png",
    "standing": 8,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "8th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "ren",
      "bne",
      "vita",
      "out",
      "imp"
    ],
    "buchholtz": 4,
    "code": "forz",
    "name": "forZe",
    "seed": 11,
    "description": "EUA #5",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/forz_large.png",
    "standing": 9,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "9th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "ihc",
      "vita",
      "mibr",
      "spir",
      "liq"
    ],
    "buchholtz": 3,
    "code": "astr",
    "name": "Astralis",
    "seed": 12,
    "description": "EUB #6",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/astr_large.png",
    "standing": 10,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "10th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "out",
      "nine",
      "astr",
      "eter",
      "bne"
    ],
    "buchholtz": -3,
    "code": "mibr",
    "name": "MIBR",
    "seed": 14,
    "description": "AM #2",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/mibr_large.png",
    "standing": 11,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "11th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "vita",
      "ihc",
      "out",
      "liq"
    ],
    "buchholtz": 4,
    "code": "cplx",
    "name": "Complexity Gaming",
    "seed": 20,
    "description": "AM #4",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/cplx_large.png",
    "standing": 12,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "12th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "bne",
      "ren",
      "spir",
      "mibr"
    ],
    "buchholtz": -1,
    "code": "eter",
    "name": "Eternal Fire",
    "seed": 17,
    "description": "EUA #7",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/eter_large.png",
    "standing": 13,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "13th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "astr",
      "cplx",
      "ren",
      "imp"
    ],
    "buchholtz": -5,
    "code": "ihc",
    "name": "IHC Esports",
    "seed": 21,
    "description": "AP #1",
    "region": "AP",
    "logo": "https://img.majors.im/go/antwerp2022/ihc_large.png",
    "standing": 14,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "14th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 0,
    "opponents": [
      "ence",
      "mibr",
      "liq"
    ],
    "buchholtz": 2,
    "code": "nine",
    "name": "9z Team",
    "seed": 24,
    "description": "AM #6",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/nine_large.png",
    "standing": 15,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "15th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 0,
    "opponents": [
      "forz",
      "eter",
      "ihc"
    ],
    "buchholtz": -5,
    "code": "ren",
    "name": "Renegades",
    "seed": 22,
    "description": "AP #2",
    "region": "AP",
    "logo": "https://img.majors.im/go/antwerp2022/ren_large.png",
    "standing": 16,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "16th",
    "elim": true,
    "adv": false,
    "currentRound": false
  }
];

export const LegendResults = [
  {
    "l": 0,
    "w": 3,
    "opponents": [
      "furi",
      "hero",
      "cope"
    ],
    "buchholtz": 3,
    "code": "spir",
    "name": "Team Spirit",
    "seed": 12,
    "description": "3-1, +1",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/spir_large.png",
    "standing": 1,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "1st",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 0,
    "w": 3,
    "opponents": [
      "g2",
      "big",
      "nip"
    ],
    "buchholtz": -1,
    "code": "navi",
    "name": "Natus Vincere",
    "seed": 8,
    "description": "EUA #4",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/navi_large.png",
    "standing": 2,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "2nd",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "faze",
      "cope",
      "out",
      "hero"
    ],
    "buchholtz": 2,
    "code": "ence",
    "name": "ENCE",
    "seed": 11,
    "description": "3-1, +3",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/ence_large.png",
    "standing": 3,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "3rd",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "vita",
      "c9",
      "navi",
      "furi"
    ],
    "buchholtz": 1,
    "code": "nip",
    "name": "Ninjas in Pyjamas",
    "seed": 7,
    "description": "EUB #3",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/nip_large.png",
    "standing": 4,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "4th",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 1,
    "w": 3,
    "opponents": [
      "ence",
      "bne",
      "c9",
      "cope"
    ],
    "buchholtz": -2,
    "code": "faze",
    "name": "FaZe Clan",
    "seed": 6,
    "description": "EUA #3",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/faze_large.png",
    "standing": 5,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "5th",
    "elim": false,
    "adv": true,
    "currentRound": false
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "bne",
      "ence",
      "spir",
      "faze",
      "imp"
    ],
    "buchholtz": 3,
    "code": "cope",
    "name": "Copenhagen Flames",
    "seed": 2,
    "description": "EUB #1",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/cope_large.png",
    "standing": 6,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "6th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "liq",
      "spir",
      "g2",
      "ence",
      "vita"
    ],
    "buchholtz": 0,
    "code": "hero",
    "name": "Heroic",
    "seed": 1,
    "description": "EUA #1",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/hero_large.png",
    "standing": 7,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "7th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 2,
    "w": 3,
    "opponents": [
      "spir",
      "liq",
      "big",
      "nip",
      "g2"
    ],
    "buchholtz": -1,
    "code": "furi",
    "name": "FURIA Esports",
    "seed": 5,
    "description": "AM #1",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/furi_large.png",
    "standing": 8,
    "status": "advanced",
    "until": 8,
    "abbrev": "A",
    "statusPositioned": true,
    "ordinalStanding": "8th",
    "elim": false,
    "adv": true,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "navi",
      "imp",
      "hero",
      "out",
      "furi"
    ],
    "buchholtz": 2,
    "code": "g2",
    "name": "G2 Esports",
    "seed": 9,
    "description": "3-0, +5",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/g2_large.png",
    "standing": 9,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "9th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "nip",
      "out",
      "liq",
      "big",
      "hero"
    ],
    "buchholtz": -4,
    "code": "vita",
    "name": "Team Vitality",
    "seed": 10,
    "description": "3-0, -4",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/vita_large.png",
    "standing": 10,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "10th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 2,
    "opponents": [
      "big",
      "g2",
      "bne",
      "c9",
      "cope"
    ],
    "buchholtz": -7,
    "code": "imp",
    "name": "Imperial Esports",
    "seed": 14,
    "description": "3-2, +1",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/imp_large.png",
    "standing": 11,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "11th",
    "elim": true,
    "adv": false,
    "currentRound": true
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "imp",
      "navi",
      "furi",
      "vita"
    ],
    "buchholtz": 2,
    "code": "big",
    "name": "BIG",
    "seed": 3,
    "description": "EUA #2",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/big_large.png",
    "standing": 12,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "12th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "out",
      "nip",
      "faze",
      "imp"
    ],
    "buchholtz": 1,
    "code": "c9",
    "name": "Cloud9",
    "seed": 4,
    "description": "EUB #2",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/c9_large.png",
    "standing": 13,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "13th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 1,
    "opponents": [
      "c9",
      "vita",
      "ence",
      "g2"
    ],
    "buchholtz": -2,
    "code": "out",
    "name": "Outsiders",
    "seed": 13,
    "description": "3-1, -2",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/out_large.png",
    "standing": 14,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "14th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 0,
    "opponents": [
      "cope",
      "faze",
      "imp"
    ],
    "buchholtz": 2,
    "code": "bne",
    "name": "Bad News Eagles",
    "seed": 15,
    "description": "3-2, -1",
    "region": "EU",
    "logo": "https://img.majors.im/go/antwerp2022/bne_large.png",
    "standing": 15,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "15th",
    "elim": true,
    "adv": false,
    "currentRound": false
  },
  {
    "l": 3,
    "w": 0,
    "opponents": [
      "hero",
      "furi",
      "vita"
    ],
    "buchholtz": 1,
    "code": "liq",
    "name": "Team Liquid",
    "seed": 16,
    "description": "3-2, -2",
    "region": "AM",
    "logo": "https://img.majors.im/go/antwerp2022/liq_large.png",
    "standing": 16,
    "status": "eliminated",
    "until": 16,
    "abbrev": "E",
    "statusPositioned": true,
    "ordinalStanding": "16th",
    "elim": true,
    "adv": false,
    "currentRound": false
  }
];
