// prettier-ignore

export const initialDataLegends = [
  {
    "code": "navi",
    "name": "Natus Vincere",
    seed: 1,
    description: "EUA #1",
    region: "EU",
  },
  {
    "code": "fnat",
    "name": "Fnatic",
    seed: 2,
    description: "EUB #1",
    region: "EU",
  },
  {
    "code": "eu1#nip",
    "name": "EUA #2",
    seed: 3,
    description: "EUA #2",
    region: "EU",
  },
  {
    "code": "eu2#ence",
    "name": "EUB #2",
    seed: 4,
    description: "EUB #2",
    region: "EU",
  },
  {
    "code": "itb",
    "name": "Into The Breach",
    seed: 5,
    description: "EUA #3",
    region: "EU",
  },
  {
    "code": "eu2#hero",
    "name": "EUB #3",
    seed: 6,
    description: "EUB #3",
    region: "EU",
  },
  {
    "code": "bne",
    "name": "Bad News Eagles",
    seed: 7,
    description: "EUA #4",
    region: "EU",
  },
  {
    "code": "eu2#4",
    "name": "EUB #4",
    seed: 8,
    description: "EUB #4",
    region: "AM",
  },
];

export const initialDataChallenger = [
  {
    "code": "eu2#5",
    "name": "EUB #5",
    "seed": 9,
    description: "EUB #5",
    region: "EU",
  },
  {
    "code": "gl",
    "name": "GamerLegion",
    seed: 10,
    description: "EUA #5",
    region: "EU",
  },
  {
    "code": "am#2",
    "name": "AM #2",
    seed: 11,
    description: "AM #2",
    region: "AM",
  },
  {
    "code": "eu2#11",
    "name": "EUB #6",
    seed: 12,
    description: "EUB #6",
    region: "EU",
  },
  {
    "code": "eu1#12",
    "name": "EUA #6",
    seed: 13,
    region: "EU",
    description: "EUA #6",
  },
  {
    "code": "eu2#13",
    "name": "EUB #7",
    seed: 14,
    description: "EUB #7",
    region: "EU",
  },
  {
    "code": "eu1#14",
    "name": "EUA #7",
    seed: 15,
    description: "EUA #7",
    region: "EU",
  },
  {
    "code": "am#2",
    "name": "AM #2",
    seed: 16,
    description: "AM #2",
    region: "AM",
  },
  {
    "code": "eu2#15",
    "name": "EUB #8",
    seed: 17,
    description: "EUB #8",
    region: "EU",
  },
  {
    "code": "eu1#16",
    "name": "EUA #8",
    seed: 18,
    description: "EUA #8",
    region: "EU",
  },
  {
    "code": "am#3",
    "name": "AM #3",
    seed: 19,
    description: "AM #3",
    region: "AM",
  },
  {
    "code": "am#4",
    "name": "AM #5",
    seed: 20,
    description: "AM #4",
    region: "AM",
  },
  {
    "code": "eu3#17",
    "name": "EU-TB",
    seed: 21,
    description: "EU-TB",
    region: "EU",
  },
  {
    "code": "ghg",
    "name": "Grayhound Gaming",
    seed: 22,
    description: "AP #1",
    region: "AP",
  },
  {
    "code": "am#5",
    "name": "AM #5",
    seed: 23,
    description: "AM #5",
    region: "AM",
  },
  {
    "code": "asia#2",
    "name": "AP#2",
    seed: 24,
    description: "AP #2",
    region: "AP",
  },
];
