// prettier-ignore

export const initialDataLegends = [
  {
    "code": "eu/faze",
    "name": "FaZe Clan",
    seed: 1,
    description: "EUA #1",
    region: "EU",
  },
  {
    "code": "eu/navi",
    "name": "Natus Vincere",
    seed: 2,
    description: "EUB #1",
    region: "EU",
  },
  {
    "code": "eu/nip",
    "name": "Ninjas in Pyjamas",
    seed: 3,
    description: "EUA #2",
    region: "EU",
  },
  {
    "code": "eu/ence",
    "name": "ENCE",
    seed: 4,
    description: "EUB #2",
    region: "EU",
  },
  {
    "code": "eu/spro",
    "name": "Sprout",
    seed: 5,
    description: "EUA #3",
    region: "EU",
  },
  {
    "code": "eu/hero",
    "name": "Heroic",
    seed: 6,
    description: "EUB #3",
    region: "EU",
  },
  {
    "code": "eu/spir",
    "name": "Team Spirit",
    seed: 7,
    description: "EUA #4",
    region: "EU",
  },
  {
    "code": "am/liqu",
    "name": "Team Liquid",
    seed: 8,
    description: "AM #1",
    region: "AM",
  },
];

export const initialDataChallenger = [
  {
    "code": "eu/og",
    "name": "OG",
    "seed": 9,
    "description": "EUB #4",
    region: "EU",
  },
  {
    "code": "eu/vita",
    "name": "Team Vitality",
    seed: 10,
    description: "EUB #5",
    region: "EU",
  },
  {
    "code": "am/eg",
    "name": "Evil Geniuses",
    seed: 11,
    description: "AM #2",
    region: "EU",
  },
  {
    "code": "eu/c9",
    "name": "Cloud9",
    seed: 12,
    description: "EUA #5",
    region: "EU",
  },
  {
    "code": "eu/big",
    "name": "BIG",
    seed: 13,
    region: "EU",
    description: "EUB #6",
  },
  {
    "code": "eu/bne",
    "name": "Bad News Eagles",
    seed: 14,
    description: "EUA #7",
    region: "EU",
  },
  {
    "code": "eu/mouz",
    "name": "MOUZ",
    seed: 15,
    description: "EUB #7",
    region: "EU",
  },
  {
    "code": "am/9z",
    "name": "9z Team",
    seed: 16,
    description: "AM #3",
    region: "AM",
  },
  {
    "code": "eu/gl",
    "name": "Team GamerLegion",
    seed: 17,
    description: "EUA #7",
    region: "EU",
  },
  {
    "code": "eu/outs",
    "name": "Outsiders",
    seed: 18,
    description: "EUB #8",
    region: "EU",
  },
  {
    "code": "am/00",
    "name": "00 Nation",
    seed: 19,
    description: "AM #4",
    region: "AM",
  },
  {
    "code": "am/furi",
    "name": "FURIA Esports",
    seed: 20,
    description: "AM #5",
    region: "AM",
  },
  {
    "code": "eu/fnat",
    "name": "Fnatic",
    seed: 21,
    description: "EUA #8",
    region: "EU",
  },
  {
    "code": "ap/ihc",
    "name": "IHC Esports",
    seed: 22,
    description: "AP #1",
    region: "AP",
  },
  {
    "code": "am/impe",
    "name": "Imperial Esports",
    seed: 23,
    description: "AM #6",
    region: "AM",
  },
  {
    "code": "ap/ghg",
    "name": "Grayhound Gaming",
    seed: 24,
    description: "AP #2",
    region: "AP",
  },
];
